---
title: Analyzing Bangalore - Population (Part 2 - Slopegraph)
author: Shyam Valsan
date: '2017-11-25'
slug: analyzing-bangalore-population-slopegraph
categories:
  - blog
  - data exploration
  - data science
  - R
tags:
  - Bangalore
  - bengaluru
  - R
  - population
  - slopegraph
---

This is part 2 of of the population analysis of Bangalore using R. In [part 1 we explored how to make animated choropleth on timeseries populataion data](https://www.shyamvalsan.com/blog/analyzing-bangalore-population-animated-choropleth-timeseries/). While the previous visualization we did was geographical in nature, this time we’re going to visualize Bangalore population data using a slopegraph. Slopegraphs help paint a before and after story by providing insights into ranking, magnitude and changes over time. [Part 3](https://shyamvalsan.com/blog/analyzing-bangalore-population-smoothed-line-graph/ ) and [Part 4](https://shyamvalsan.com/blog/analyzing-bangalore-population-bubblecharts/) are also now published.

The idea of this particular slope graph is to show how the ranking of the selected wards changed drastically between 2001 and 2011 and to predict the change between 2011 and 2021. The list of wards I have picked are a mix of the most populous wards in 2001 and 2011 and also a general sampling of well-known localities in Bangalore.

 
**Key insights**

 - Between 2001 and 2011 the geo-demographics of the city changed drastically
 - Between 2011 and 2021 this sort of change is largely absent and consolidation of the change from the previous decade is prevalent
 - Bellandur and Begur, were among the least populated wards in 2001 and just exploded in to the top 3 in ten years and are expected to stay there 

**How does the code work? **

```r
library(RColorBrewer)
library(scales)

pop <- read.csv("data/ward_popt.csv")
plot(c(0,1),c(0,1),type='n',axes=F,xlab='',ylab='') 

pop[,1]<-as.character(pop[,1]) 
listOfWards<-ncol(pop)-1
ranking<-2:ncol(pop)
pop[,ranking]<-rescale(as.matrix(pop[,ranking]),c(5,25))  #rescale so line sizes make sense

#reorder column ranking 
first.ord<-order(pop[1,ranking],decreasing=T)
pop[,ranking]<-pop[,ranking][,first.ord]
names(pop)[ranking]<-names(pop)[ranking][first.ord]

#list population of wards in decreasing order for each date
columns<-vector('list',nrow(pop))
names(columns)<-pop[,1]
for(val in 1:nrow(pop)){
  tmp<-t(pop[val,ranking])
  tmp<-tmp[order(tmp,decreasing=T),,drop=F]
  columns[[val]]<-tmp
}

# x and y co-ordinates 
x_plot<-rep(c(0.1,0.5,0.9),each=listOfWards)
x_plot<-split(x_plot,x_plot)
y_plot<-rev(seq(0,0.9,length=listOfWards+1))

# get line colors
line_colors<-alpha(colorRampPalette(c("red","yellow","green"))(listOfWards),0.7)

for(val in 1:(length(columns)-1)){
  temp_plot<-columns[c(val,val+1)]
  x_tmp<-x_plot[c(val,val+1)]
  rowtxt <- row.names(temp_plot[[1]])
  text(x_tmp[[1]],y_plot,rowtxt)
  
  if(val == length(columns)-1){
    rowtxt <- row.names(temp_plot[[2]])
    text(x_tmp[[2]],y_plot,rowtxt)
    heading<-substitute(bold(x),list(x=names(temp_plot)[2]))
    text(unique(x_tmp[[2]]),y.locs[2],heading)
  }	
  
  heading<-substitute(bold(x),list(x=names(temp_plot)[1]))  
  text(unique(x_tmp[[1]]),y.locs[2],heading)
  
  sort_names<-match(row.names(temp_plot[[1]]),row.names(temp_plot[[2]]))
  line_width<-temp_plot[[1]][,1]
  
  segments(x_tmp[[1]], y_plot, x_tmp[[2]], y_plot[sort_names], col=line_colors, lwd=line_width)
  
  sort_colors<-match(row.names(temp_plot[[2]]),row.names(temp_plot[[1]]))
  line_colors<-line_colors[sort_colors]
}
```

**Data sources**

[BBMP ward data](http://bbmp.gov.in/documents/10180/460906/BBMPR_ward_master_BBMP+Restructuring+03-08-2015.pdf/)

**References**

[http://journocode.com](http://journocode.com/2016/01/28/your-first-choropleth-map/)

*Suggestions and corrections are always welcome, please use the comments section.*