---
title: Analyzing Bangalore - Population (Part 3 - Smoothed Line Graph)
author: Shyam Valsan
date: '2017-11-27'
slug: analyzing-bangalore-population-smoothed-line-graph
categories:
  - blog
  - data exploration
  - data science
  - R
tags:
  - Bangalore
  - bengaluru
  - population
  - R
  - line graph
  - growth rate
---

This is a simple smoothed line chart of population growth rate over time, and yet it is very revealing.

```{r}
library(ggplot2)
blr_growth_rate <- read.csv("BangaloreGrowthRate.csv")

ggplot(blr_growth_rate,aes(x = Time,y = GrowthRate )) +
  geom_point(aes(colour = GrowthRate)) +
  scale_colour_gradient2(low = "blue", mid = "green" , high = "red", midpoint = 3.5) + 
  geom_smooth(colour = "blue",size = 0.9) +
  scale_y_continuous(limits = c(1,7), breaks = seq(1,7,1)) +
  scale_x_continuous(limits = c(1955,2030), breaks = seq(1960,2030,10)) +
  ggtitle ("Average Annual Rate of Change of Population in Bangalore") +
  xlab("Year") +  ylab ("Average Growth Rate %")
```

*Key takeaways*

 - Population growth peaked in the late 1970s, reaching its zenith around 1980
 - After which there was a downward trend for the next 20 years, before another spike, a smaller one this time
 - This second spike in population growth was between the years 2000 and 2010 peaking around 2009
 - The downward trend which started around 2010 is expected to continue till 2030 and beyond until an event that comes along to change the geo-socio-economic dynamic of the city

 
 Let's examine the two periods of rapid growth in population which Bangalore has experienced in the last 70 years.

 - Population growth rate grew continuously post-independence, peaking between 1975 and 1980, with immigrants flocking to the city from other parts of Karnataka and outside the state.
 - Manufacturing plants setup around the city also attracted a large floating population to the city during this period
 - The second period of growth appears to be strongly correlated to the IT boom, as software companies mushroomed a whole eco system developed with construction, retail, small businesses, restaurants and almost all sections of the society experiencing an influx in people from all over India.

**Data sources**

[United Nations Top 30 Urban Agglomerations - Population and Growth Rate](https://esa.un.org/Unpd/Wup/CD-ROM/)

*Suggestions and corrections are always welcome, please use the comments section.*