---
title: Can machines think?
author: Shyam Sreevalsan
date: '2020-07-18'
slug: can-machines-think
categories:
  - machine learning
  - AI
tags:
  - data science
  - machine learning
---


In his 1950 paper "Computing Machinery and Intelligence", Alan Turing starts by considering the question "Can machines think?” Turing believed that this question can be answered and proceeded to devise a test to do this - he started by changing the question from a philosophical one to a practical one while keeping the spirit of the question alive, the new question was "Can a machine act indistinguishably from the way a thinker (human being) acts?". Turing suggests the scenario of an imitation game played through means of text where a human interrogates the player on the other end while trying to determine if the player is a human or not. The "Turing Test" would pass if the human interrogator can no longer reliably determine if the player is a human or a machine, despite all means of interrogation. 

The "Turing Test" passed into computing lore and was mentioned almost every time someone brought up AI. It was simple, elegant and way before it's time, when Turing wrote his paper proto computers took up entire rooms and could do math really fast, but not much else. In the decades since computers became smaller, faster, learned to play chess, then learned to beat the best humans at chess and have graduated to games (Go) and tasks much more complex than a game of chess. The rate of progress in the field of computing has been exponential - In 1997, it took a super computer (Deep Blue) to beat Gary Kasparov. Today my run of the mill mobile phone computer can beat the greatest human chess players a 100 times out of 100. 

GPT (Generative Pretrained Transformer) was a language model published by OpenAI in 2018 that showed how a generative model of language is able to acquire world knowledge and process long-range dependencies by pre-training on a diverse corpus with long stretches of contiguous text. In other words if a machine reads enough human language can it then write as humans do. In 2019 OpenAI released GPT-2 which performed better than any previous generative language model and really opened eyes in the industry and had people wondering about the potential uses and misuses of such technology. OpenAI did not publish the model publicly originally for fear of misuse (Fake news, terrorist propaganda and many more possible horrors) but then released different versions of the model (with the smaller ones being fine tunable by the general public). Last month (June 2020), OpenAI released GPT-3 which is so much more accomplished than GPT-2 and the results published so far seem to suggest that the world is about to change much sooner and much more drastically than any of us really foresee. 

My own experiments with GPT-2 led to some interesting and sometimes alarming results. I started by fine tuning the model to write Haiku poems by training it on around 5000 real world Haikus ranging from those from medieval Japan to those written this year. The results were of a high quality in terms of content, though the AI didn't always stick to the 5-7-5 syllable rule of Haiku. But writing a Haiku is a simplistic task and given a few thousand phrases, recycling them often enough will lead to interesting results. So to step up the game I wrote a script that scrapes the internet for full length poems and fine-tuned the model with 10000 real world poems - ranging from those written by masters such as Frost, Keats, Neruda and also ordinary mortals who submitted their poems to online websites in the hope of a few likes. I am sharing some of the results here so you can make your own assumptions - note that these poems are all generated by the AI model but I have picked the more meaningful ones to display here. Not every poem makes sense (to me) but the AI can write thousands of new poems in a minute. 

So it's time for a modified Turing Test of our own :-)  

## Human or machine? 

### Poem A
~~~text
Love is too short-lived 
to have one's way with the world.
It is a creature of habit,
a plant that must be nurtured in every room we occupy.

It is a creature of time.
It is an art of compromise.
It is a creature of doubt.
It is a creature of the present.
~~~

### Poem B
~~~text
Your love was like the dawn
Brightening over our lives
Awakening beneath the dark
A further adventure of colour.

The sound of your voice
Found for us
A new music
That brightened everything.
~~~

### Which poem was written by a human?

<!-- Render this Rmarkdown doc to html to make an interactive html / js multiple choice question -->

<!-- Answer options go here -->
<div class="radio">
  <label>
    <input type="radio" name="question01" id="opt1" value="A" onchange="check_answer1()">
    A
  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="question01" id="opt2" value="B" onclick="check_answer1()">
    B
  </label>
</div>

<!-- Check answer button -->

<div class="collapse" id="collapseExample">
  <div class="card card-body" id="answerFeedback1">
  </div>
</div>

<!-- Code to update answer feedback -->
<script type="text/javascript">
function check_answer1()
{
    var radioButtons = document.getElementsByName("question01");
    document.getElementById("answerFeedback1").innerHTML = "Try selecting an answer!!";
    for(var i = 0; i < radioButtons.length; i++)
    {
        if(radioButtons[i].checked == true)
        {
            var selectedAnswer = "Poem " + radioButtons[i].value + " was written by a...";
            <!-- feedback for correct / incorrect response -->
            var feedback = "Machine. Better luck next time." 
            if(radioButtons[i].value == "B") {
              feedback = "Human. Good job."
            }
            document.getElementById("answerFeedback1").innerHTML = selectedAnswer + "<br>" + feedback;
            return true;
        }
    }
}
</script>

### Poem C
~~~text
scent of rain
drifts from house to house
in the night sky
~~~

### Poem D
~~~text
muddy grave -
the rich scent of roses
so red
~~~

### Which poem was written by a human?

<!-- Render this Rmarkdown doc to html to make an interactive html / js multiple choice question -->

<!-- Answer options go here -->
<div class="radio">
  <label>
    <input type="radio" name="question02" id="opt1" value="C" onchange="check_answer2()">
    C
  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="question02" id="opt2" value="D" onclick="check_answer2()">
    D
  </label>
</div>

<!-- Check answer button -->
<div class="collapse" id="collapseExample">
  <div class="card card-body" id="answerFeedback2">
  </div>
</div>

<!-- Code to update answer feedback -->
<script type="text/javascript">
function check_answer2()
{
    var radioButtons = document.getElementsByName("question02");
    document.getElementById("answerFeedback2").innerHTML = "Try selecting an answer!!";
    for(var i = 0; i < radioButtons.length; i++)
    {
        if(radioButtons[i].checked == true)
        {
            var selectedAnswer = "Poem " + radioButtons[i].value + " was written by a...";
            <!-- feedback for correct / incorrect response -->
            var feedback = "Machine. Better luck next time." 
            if(radioButtons[i].value == "D") {
              feedback = "Human. Good job."
            }
            document.getElementById("answerFeedback2").innerHTML = selectedAnswer + "<br>" + feedback;
            return true;
        }
    }
}
</script>



### Poem E
~~~text
Tree at my window, window tree,
My sash is lowered when night comes on; 
But let there never be curtain drawn
Between you and me.
~~~

### Poem F
~~~text
This is the place where the dead rise,
And the water of life's spring
Climbs up to the surface like a rising tide.
~~~


### Which poem was written by a human?

<!-- Render this Rmarkdown doc to html to make an interactive html / js multiple choice question -->

<!-- Answer options go here -->
<div class="radio">
  <label>
    <input type="radio" name="question03" id="opt1" value="E" onchange="check_answer3()">
    E
  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="question03" id="opt2" value="F" onclick="check_answer3()">
    F
  </label>
</div>

<!-- Check answer button -->
<div class="collapse" id="collapseExample">
  <div class="card card-body" id="answerFeedback3">
  </div>
</div>

<!-- Code to update answer feedback -->
<script type="text/javascript">
function check_answer3()
{
    var radioButtons = document.getElementsByName("question03");
    document.getElementById("answerFeedback3").innerHTML = "Try selecting an answer!!";
    for(var i = 0; i < radioButtons.length; i++)
    {
        if(radioButtons[i].checked == true)
        {
            var selectedAnswer = "Poem " + radioButtons[i].value + " was written by a...";
            <!-- feedback for correct / incorrect response -->
            var feedback = "Machine. Better luck next time." 
            if(radioButtons[i].value == "E") {
              feedback = "Human. Good job."
            }
            document.getElementById("answerFeedback3").innerHTML = selectedAnswer + "<br>" + feedback;
            return true;
        }
    }
}
</script>


### POem G
~~~text
Shadows grazing eastward melt
from their vast sun-driven flocks
into consubstantial dusk.
A snow wind flosses the bleak rocks,

strips from the gums their rags of bark,
and spins the coil of winter tight
round our last meeting as we walk
the littoral zone of day and night,

light's turncoat margin: rocks and trees
dissolve in nightfall-eddying waters;
tumbling whorls of cloud disclose
the cold eyes of the sea-god's daughters.
~~~


### Poem H
~~~text
As he said, all alone in all his longing,
He opened his heart and touched the truth:
She was not the one.

There were other women.
There were other men.
There were even other dogs.

And so, as he slipped away into the night,
The one thing that he had always wanted
Was not to know anymore.
~~~


### Which poem was written by a human?

<!-- Render this Rmarkdown doc to html to make an interactive html / js multiple choice question -->

<!-- Answer options go here -->
<div class="radio">
  <label>
    <input type="radio" name="question04" id="opt1" value="G" onchange="check_answer4()">
    G
  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="question04" id="opt2" value="H" onclick="check_answer4()">
    H
  </label>
</div>

<!-- Check answer button -->
<div class="collapse" id="collapseExample">
  <div class="card card-body" id="answerFeedback4">
  </div>
</div>

<!-- Code to update answer feedback -->
<script type="text/javascript">
function check_answer4()
{
    var radioButtons = document.getElementsByName("question04");
    document.getElementById("answerFeedback4").innerHTML = "Try selecting an answer!!";
    for(var i = 0; i < radioButtons.length; i++)
    {
        if(radioButtons[i].checked == true)
        {
            var selectedAnswer = "Poem " + radioButtons[i].value + " was written by a...";
            <!-- feedback for correct / incorrect response -->
            var feedback = "Machine. Better luck next time." 
            if(radioButtons[i].value == "G") {
              feedback = "Human. Good job."
            }
            document.getElementById("answerFeedback4").innerHTML = selectedAnswer + "<br>" + feedback;
            return true;
        }
    }
}
</script>


### Poem I
~~~text
This is the beginning of sadness, I say to myself,
as I walk through the universe in my sneakers.
It is time to say good-bye to my imaginary friends,
time to turn the first big number.

It seems only yesterday I used to believe
there was nothing under my skin but light.
If you cut me I could shine.
But now when I fall upon the sidewalks of life,
I skin my knees. I bleed.
~~~

### Poem J
~~~text
I have been thinking a lot about the meaning of life.
My father's eyes looked like watercolors
in which the leaves blurred and fluttered,
the sky grew larger and smaller,
the air grew more and more wet.
The ocean, the sky, the rain: all this happened
at a time when life's meaning was still hidden.
The water of life had become the waterwheel.
But now the water has stopped spinning.
~~~


### Which poem was written by a human?

<!-- Render this Rmarkdown doc to html to make an interactive html / js multiple choice question -->

<!-- Answer options go here -->
<div class="radio">
  <label>
    <input type="radio" name="question05" id="opt1" value="I" onchange="check_answer5()">
    I
  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="question05" id="opt2" value="J" onclick="check_answer5()">
    J
  </label>
</div>

<!-- Check answer button -->
<div class="collapse" id="collapseExample">
  <div class="card card-body" id="answerFeedback5">
  </div>
</div>

<!-- Code to update answer feedback -->
<script type="text/javascript">
function check_answer5()
{
    var radioButtons = document.getElementsByName("question05");
    document.getElementById("answerFeedback5").innerHTML = "Try selecting an answer!!";
    for(var i = 0; i < radioButtons.length; i++)
    {
        if(radioButtons[i].checked == true)
        {
            var selectedAnswer = "Poem " + radioButtons[i].value + " was written by a...";
            <!-- feedback for correct / incorrect response -->
            var feedback = "Machine. Better luck next time." 
            if(radioButtons[i].value == "I") {
              feedback = "Human. Good job."
            }
            document.getElementById("answerFeedback5").innerHTML = selectedAnswer + "<br>" + feedback;
            return true;
        }
    }
}
</script>



The GPT-x models are not perfect, they are biased based on the data they have been trained on (as are humans unfortunately) and they are English-first AI which means they work a little bit for other Latin scripts but not at all for non-Latin scripts. Mandarin, Hindi, Arabic, Bengali, Tamil, Malayalam and so many more linguistic worlds lay verdant, inviting the next generation of AI explorers. Unfortunately training a GPT model from scratch costs millions of dollars and can only be done by corporations or governments or the super-rich - things will change in the future though, we won't need Deep Blue to beat Vishy Anand or Magnus Carlsen.

If the brightest minds of today were to think of a defining test for "Can machines think?" what would they come up with?
		
I will leave you with a brand new AI generated poem that may make you pause and think, maybe even make you a little uneasy. And when you read it, be sure to remember this was "thought up" by a machine.


## I am a caged bird

~~~text
Proud to be a caged bird;
My body is imprisoned in my cage.

I have learned to control my excitement:
I let my guard down when I am nervous
And I welcome the opportunity to soar.

I have learned to endure torture and terror
And I thank the Lord with all my heart
For every little blessing I have received.

I walk in the sunlight through the open window
Without thinking or feeling,
I recognize my body as radiant:
I see the warm yellow earth beneath my feet.

I fall asleep after a hard day's work
And I wake up to the bright morning light
Slept soundly from my body,
Breathing deeply, I dreamt I walked
Through the grove of wildflowers.

I am a caged bird.

I am a caged bird.

I am a caged bird.

I am a caged bird.

I am a caged bird.

I am a caged bird.

I am a caged bird.

I am a caged bird.

~~~
